FROM node:20-alpine

WORKDIR /app/backend

COPY backend/package*.json ./
RUN npm ci --omit=dev

COPY backend/bootstrap.js ./
COPY backend/src ./src
COPY database/migration /app/database/migration

CMD ["npm", "run", "migrate"]
